## Useful NLP Libraries & Networks

1) What is Computational Linguistics and how does it relate to NLP?

->

Computational Linguistics (CL) is an interdisciplinary field that focuses on the scientific study of language using computational methods. It aims to model how human language works by combining insights from:

- Linguistics (syntax, semantics, pragmatics)
- Computer Science
- Artificial Intelligence
- Mathematics and logic

The primary objective of Computational Linguistics is to formally represent linguistic knowledge so that it can be processed by machines. This includes building models for grammar, sentence structure, meaning representation, and discourse.

Natural Language Processing (NLP), on the other hand, is an applied discipline that uses computational linguistic theories along with machine learning and deep learning techniques to build real-world language-processing systems.

 Relationship Between CL and NLP
- Computational Linguistics provides the theoretical and linguistic foundation
- NLP focuses on practical implementations and applications

In simple terms:

> Computational Linguistics explains *how language works*  
> NLP applies that knowledge to solve real-world problems

Modern NLP systems often combine:
- Linguistic rules from CL  
- Statistical methods  
- Neural networks  

Thus, NLP can be seen as the engineering arm of Computational Linguistics.





 2) Briefly describe the historical evolution of Natural Language Processing.

->

The development of NLP has progressed through several important stages:

 1. Early Rule-Based Systems (1950s–1970s)
- Language processing was based on handcrafted grammatical rules.
- Linguists manually wrote syntax and grammar rules.
- Example: Early machine translation systems.
- Limitations:  
  - Difficult to scale  
  - Could not handle ambiguity  
  - High maintenance cost  



 2. Statistical NLP Era (1980s–2000s)
- Shift from rules to probability-based models.
- Use of large text corpora.
- Common models:
  - N-grams
  - Hidden Markov Models (HMMs)
  - Probabilistic Context-Free Grammars
- Advantages: Better handling of uncertainty.
- Limitations: Required large annotated datasets.



 3. Machine Learning Era (2000s–2010s)
- Introduction of supervised learning algorithms.
- Popular techniques:
  - Support Vector Machines (SVMs)
  - Conditional Random Fields (CRFs)
  - Decision Trees
- Feature engineering became critical.
- Improved accuracy over purely statistical methods.



 4. Deep Learning and Transformer Era (2015–Present)
- Use of neural networks and word embeddings.
- Breakthrough models:
  - Word2Vec, GloVe
  - RNNs, LSTMs
  - Transformers (BERT, GPT)
- Advantages:
  - Context-aware understanding
  - Minimal feature engineering
  - State-of-the-art performance across NLP tasks



 3) List and explain three major use cases of NLP in today’s tech industry.

->

 1. Conversational AI (Chatbots & Virtual Assistants)
- Examples: Customer support bots, Siri, Alexa, Google Assistant.
- NLP enables:
  - Understanding user intent
  - Context-aware conversation
  - Natural language generation
- Widely used in customer service and automation.



 2. Machine Translation
- Automatic translation between languages.
- Examples: Google Translate, DeepL.
- NLP techniques handle:
  - Syntax differences
  - Semantic meaning
  - Cultural context
- Transformers have significantly improved translation quality.



 3. Sentiment Analysis and Opinion Mining
- Identifies emotions and opinions in text.
- Used in:
  - Product reviews
  - Social media monitoring
  - Brand reputation analysis
- Helps businesses make data-driven decisions.




 4) What is text normalization and why is it essential in text processing tasks?

->

Text normalization is the process of converting raw text into a standardized and consistent format so that it can be effectively analyzed by NLP models.

 Common Text Normalization Techniques
- Converting text to lowercase  
- Removing punctuation and special characters  
- Expanding contractions (e.g., *don't → do not*)  
- Removing stopwords  
- Handling numbers and symbols  

 Why Text Normalization Is Essential
- Reduces noise and inconsistencies
- Ensures uniform word representation
- Improves model accuracy and efficiency
- Simplifies feature extraction
- Prevents duplicate representations of the same word

Example:
```
"I’m Loving NLP!!!" → "i am loving nlp"
```



 5) Compare and contrast stemming and lemmatization with suitable examples.

->

Both stemming and lemmatization are techniques used to reduce words to their base form, but they differ significantly in approach and accuracy.



 Stemming
- Uses simple rule-based heuristics.
- Removes word suffixes without understanding context.
- Output may not be a valid dictionary word.

Examples:
- *running → run*
- *studies → studi*
- *connected → connect*

Advantages: Fast and computationally cheap  
Disadvantages: Less accurate, may produce incorrect roots



 Lemmatization
- Uses linguistic rules and vocabulary.
- Considers context and part-of-speech.
- Always produces a valid dictionary word.

Examples:
- *running → run*
- *studies → study*
- *better → good*

Advantages: More accurate and meaningful  
Disadvantages: Slower and more computationally expensive



 Comparison Table

| Aspect | Stemming | Lemmatization |
|------|----------|---------------|
| Approach | Rule-based | Linguistic + dictionary-based |
| Context awareness | No | Yes |
| Output | May be invalid | Always valid |
| Speed | Fast | Slower |
| Accuracy | Lower | Higher |

In [1]:
"""
6) Write a Python program using TextBlob to perform sentiment analysis on the following paragraph of text:

“I had a great experience using the new mobile banking app. The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating"

Your program should print out the polarity and subjectivity scores.
->

"""

# Install TextBlob
!pip install textblob --quiet

# Import TextBlob
from textblob import TextBlob

# Given paragraph
text = """
I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating.
"""

# Create TextBlob object
blob = TextBlob(text)

# Perform sentiment analysis
sentiment = blob.sentiment

# Print results
print("Sentiment Analysis Results:")
print("Polarity:", sentiment.polarity)
print("Subjectivity:", sentiment.subjectivity)

Sentiment Analysis Results:
Polarity: 0.21742424242424244
Subjectivity: 0.6511363636363636


In [2]:
"""
7)  Given the sample paragraph below, perform string tokenization and frequency distribution using Python and NLTK:

“Natural Language Processing (NLP) is a fascinating field that combines linguistics, computer science, and artificial intelligence.
It enables machines to understand, interpret, and generate human language. Applications of NLP include chatbots, sentiment analysis, and
machine translation.As technology advances, the role of NLP in modern solutions is becoming increasingly critical.”

->

"""

# Import required libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Download required NLTK resources (run once)
nltk.download('punkt')

# Given paragraph
text = """
Natural Language Processing (NLP) is a fascinating field that combines linguistics, computer science, and artificial intelligence.
It enables machines to understand, interpret, and generate human language. Applications of NLP include chatbots, sentiment analysis, and
machine translation. As technology advances, the role of NLP in modern solutions is becoming increasingly critical.
"""

# Step 1: Tokenization
tokens = word_tokenize(text)

print("Tokens:")
print(tokens)

# Step 2: Frequency Distribution
freq_dist = FreqDist(tokens)

print("\nFrequency Distribution:")
for word, freq in freq_dist.items():
    print(f"{word} : {freq}")

Tokens:
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '.', 'It', 'enables', 'machines', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'Applications', 'of', 'NLP', 'include', 'chatbots', ',', 'sentiment', 'analysis', ',', 'and', 'machine', 'translation', '.', 'As', 'technology', 'advances', ',', 'the', 'role', 'of', 'NLP', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical', '.']

Frequency Distribution:
Natural : 1
Language : 1
Processing : 1
( : 1
NLP : 3
) : 1
is : 2
a : 1
fascinating : 1
field : 1
that : 1
combines : 1
linguistics : 1
, : 7
computer : 1
science : 1
and : 3
artificial : 1
intelligence : 1
. : 4
It : 1
enables : 1
machines : 1
to : 1
understand : 1
interpret : 1
generate : 1
human : 1
language : 1
Applications : 1
of : 2
include : 1
chatbots : 1
sentiment : 1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [3]:
"""
8)  Implement a basic LSTM model in Keras for a text classification task using
the following dummy dataset. Your model should classify sentences as either positive
(1) or negative (0).

# Dataset
texts = [
“I love this project”, #Positive
“This is an amazing experience”, #Positive
“I hate waiting in line”, #Negative
“This is the worst service”, #Negative
“Absolutely fantastic!” #Positive
]

labels = [1, 1, 0, 0, 1]

Preprocess the text, tokenize it, pad sequences, and build an LSTM model to train on
this data. You may use Keras with TensorFlow backend.

->

"""

# Install TensorFlow (if not already installed)
!pip install tensorflow --quiet

# -----------------------------
# Import required libraries
# -----------------------------
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# -----------------------------
# Dataset
# -----------------------------
texts = [
    "I love this project",                # Positive
    "This is an amazing experience",      # Positive
    "I hate waiting in line",              # Negative
    "This is the worst service",           # Negative
    "Absolutely fantastic"                # Positive
]

labels = [1, 1, 0, 0, 1]

# Convert labels to NumPy array (IMPORTANT)
labels = np.array(labels)

# -----------------------------
# Step 1: Tokenization
# -----------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
word_index = tokenizer.word_index

print("Word Index:")
print(word_index)

# -----------------------------
# Step 2: Padding Sequences
# -----------------------------
max_length = 6
padded_sequences = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post'
)

print("\nPadded Sequences:")
print(padded_sequences)

# -----------------------------
# Step 3: Build LSTM Model
# -----------------------------
vocab_size = len(word_index) + 1  # +1 for padding token

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_length=max_length),
    LSTM(32),
    Dense(1, activation='sigmoid')
])

# -----------------------------
# Step 4: Compile Model
# -----------------------------
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -----------------------------
# Step 5: Train Model
# -----------------------------
model.fit(
    padded_sequences,
    labels,
    epochs=20,
    verbose=1
)

# -----------------------------
# Step 6: Test the Model
# -----------------------------
test_text = ["I really love this experience"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq, maxlen=max_length, padding='post')

prediction = model.predict(test_pad)

print("\nTest Sentence:", test_text[0])
print("Predicted Sentiment Score:", prediction[0][0])
print("Predicted Label:", 1 if prediction[0][0] > 0.5 else 0)

Word Index:
{'this': 1, 'i': 2, 'is': 3, 'love': 4, 'project': 5, 'an': 6, 'amazing': 7, 'experience': 8, 'hate': 9, 'waiting': 10, 'in': 11, 'line': 12, 'the': 13, 'worst': 14, 'service': 15, 'absolutely': 16, 'fantastic': 17}

Padded Sequences:
[[ 2  4  1  5  0  0]
 [ 1  3  6  7  8  0]
 [ 2  9 10 11 12  0]
 [ 1  3 13 14 15  0]
 [16 17  0  0  0  0]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.4000 - loss: 0.6945
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6932
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.6920
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.6909
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6898
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.6887
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6000 - loss: 0.6876
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6000 - loss: 0.6865
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6000 - loss: 0.6854
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6843
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.6831
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6819
Epo

In [4]:
"""
9) Using spaCy, build a simple NLP pipeline that includes tokenization,
lemmatization, and entity recognition. Use the following paragraph as your dataset:

“Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India.”

Write a Python program that processes this text using spaCy, then prints tokens, their
lemmas, and any named entities found.

->

"""

# Install spaCy
!pip install spacy --quiet

# Download the English language model
!python -m spacy download en_core_web_sm

# -----------------------------
# Import spaCy and load model
# -----------------------------
import spacy

nlp = spacy.load("en_core_web_sm")

# -----------------------------
# Given paragraph
# -----------------------------
text = """
Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role in the
development of India’s atomic energy program. He was the founding director of the Tata
Institute of Fundamental Research (TIFR) and was instrumental in establishing the
Atomic Energy Commission of India.
"""

# -----------------------------
# Process text using spaCy
# -----------------------------
doc = nlp(text)

# -----------------------------
# Tokenization and Lemmatization
# -----------------------------
print("Tokens and Lemmas:")
for token in doc:
    if not token.is_space:
        print(f"Token: {token.text:<20} Lemma: {token.lemma_}")

# -----------------------------
# Named Entity Recognition
# -----------------------------
print("\nNamed Entities:")
for ent in doc.ents:
    print(f"Entity: {ent.text:<45} Label: {ent.label_}")

  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Tokens and Lemmas:
Token: Homi                 Lemma: Homi
Token: Jehangir             Lemma: Jehangir
Token: Bhaba                Lemma: Bhaba
Token: was                  Lemma: be
Token: an                   Lemma: an
Token: Indian               Lemma: indian
Token: nuclear              Lemma: nuclear
Token: physicist            Lemma: physicist
Token: who                  Lemma: who
Token: played               Lemma: play
Token: a                    Lemma: a
Token: key                  Lemma: key
Token: role    

10) You are working on a chatbot for a mental health platform. Explain how
you would leverage LSTM or GRU networks along with libraries like spaCy or Stanford NLP to understand and respond to user input effectively. Detail your architecture, data preprocessing pipeline, and any ethical considerations.

->

Designing a Mental Health Chatbot Using LSTM / GRU and NLP Libraries

When building a chatbot for a mental health platform, the goal is not only to understand user input accurately but also to respond in a safe, empathetic, and ethical manner. Recurrent neural networks such as LSTM or GRU, combined with NLP libraries like spaCy or Stanford NLP, provide an effective foundation for such systems.

 1. Overall System Architecture

A typical mental health chatbot architecture consists of the following components:

1. User Input Layer
2. Text Preprocessing & NLP Pipeline
3. Sequence Modeling (LSTM / GRU)
4. Intent & Emotion Classification
5. Response Generation or Retrieval
6. Safety & Ethics Layer
7. User Response Output



 2. Data Preprocessing Pipeline

Preprocessing is critical because user input may be informal, emotional, or unstructured.

Steps in Preprocessing
- Text Cleaning
  - Lowercasing
  - Removing unnecessary punctuation
  - Handling emojis and special characters
- Tokenization
  - Split text into words or subwords
  - spaCy or Stanford NLP tokenizers ensure linguistic accuracy
- Lemmatization
  - Convert words to base form (e.g., *feeling → feel*)
- Stopword Handling
  - Remove irrelevant words where appropriate
- Sentence Segmentation
  - Important for long user messages

Role of NLP Libraries
- spaCy: Fast tokenization, lemmatization, POS tagging, NER  
- Stanford NLP: Deep linguistic analysis, dependency parsing, coreference resolution  

These tools help extract meaningful linguistic features before modeling.


 3. Role of LSTM / GRU Networks

User conversations are sequential and depend heavily on context.  
LSTM and GRU networks are ideal because they can model temporal dependencies in text.

Why LSTM / GRU?
- Maintain memory of previous words and sentences
- Handle long-term dependencies
- Reduce vanishing gradient issues seen in vanilla RNNs

LSTM vs GRU
- LSTM: Better for very long and complex conversations
- GRU: Faster, simpler, and often sufficient for chatbot tasks


 4. Model Architecture (High-Level)

1. Embedding Layer
   - Converts tokens into dense vectors
   - Can use pretrained embeddings (GloVe, Word2Vec)
2. LSTM / GRU Layer
   - Captures context and emotional flow
3. Dense Layers
   - Used for intent classification or emotion detection
4. Output Layer
   - Predicts:
     - User intent (e.g., anxiety, sadness, stress)
     - Emotional state
     - Appropriate response category


 5. Understanding User Intent and Emotion

The chatbot must identify:
- Emotional state (sad, anxious, angry, neutral)
- Intent (seeking help, venting, asking advice)

# Techniques Used
- LSTM/GRU-based emotion classification
- Sentiment analysis as a supporting signal
- Context tracking across multiple turns

This helps the chatbot choose responses that are empathetic and relevant.


 6. Response Generation Strategy

Two main approaches can be used:

1. Retrieval-Based Responses
- Select the best response from a predefined, therapist-approved set
- Safer and more controllable
- Preferred for mental health applications

2. Generative Responses
- Use sequence-to-sequence LSTM/GRU models
- Generates responses dynamically
- Requires strong safety filters and monitoring

In mental health platforms, retrieval-based systems are often preferred due to safety concerns.


 7. Ethical and Safety Considerations

Ethics are crucial in mental health chatbots.

 Key Ethical Concerns
- User Privacy
  - Encrypt conversations
  - Comply with data protection laws
- Emotional Safety
  - Avoid harmful or dismissive responses
  - Never replace professional medical advice
- Bias and Fairness
  - Ensure training data is diverse and unbiased
- Crisis Handling
  - Detect suicidal or self-harm intent
  - Escalate to human professionals or emergency resources
- Transparency
  - Clearly inform users that the chatbot is not a human therapist


 8. Continuous Improvement and Monitoring

- Log anonymized interactions for improvement
- Regularly retrain models with updated data
- Human-in-the-loop review for critical cases
- Monitor false positives and false negatives in emotion detection



Conclusion

By combining LSTM or GRU networks with powerful NLP tools like spaCy or Stanford NLP, a mental health chatbot can effectively understand user language, context, and emotions. However, success depends not only on technical accuracy but also on ethical design, safety mechanisms, and responsible deployment. Such systems should support users empathetically while encouraging professional help when necessary.